# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails-footnotes}
  s.version = "3.6.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Keenan Brock"]
  s.date = %q{2010-11-07}
  s.description = %q{Every Rails page has footnotes that gives information about your application and links back to your editor.}
  s.email = %q{keenan@thebrocks.net}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGELOG",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "lib/rails-footnotes.rb",
     "lib/rails-footnotes/backtracer.rb",
     "lib/rails-footnotes/footnotes.rb",
     "lib/rails-footnotes/notes/abstract_note.rb",
     "lib/rails-footnotes/notes/assigns_note.rb",
     "lib/rails-footnotes/notes/controller_note.rb",
     "lib/rails-footnotes/notes/cookies_note.rb",
     "lib/rails-footnotes/notes/env_note.rb",
     "lib/rails-footnotes/notes/files_note.rb",
     "lib/rails-footnotes/notes/filters_note.rb",
     "lib/rails-footnotes/notes/general_note.rb",
     "lib/rails-footnotes/notes/javascripts_note.rb",
     "lib/rails-footnotes/notes/layout_note.rb",
     "lib/rails-footnotes/notes/log_note.rb",
     "lib/rails-footnotes/notes/params_note.rb",
     "lib/rails-footnotes/notes/partials_note.rb",
     "lib/rails-footnotes/notes/queries_note.rb",
     "lib/rails-footnotes/notes/routes_note.rb",
     "lib/rails-footnotes/notes/rpm_note.rb",
     "lib/rails-footnotes/notes/session_note.rb",
     "lib/rails-footnotes/notes/stylesheets_note.rb",
     "lib/rails-footnotes/notes/view_note.rb"
  ]
  s.homepage = %q{http://github.com/josevalim/rails-footnotes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rails-footnotes}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Every Rails page has footnotes that gives information about your application and links back to your editor.}
  s.test_files = [
    "test/footnotes_test.rb",
     "test/notes/abstract_note_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

